version: '3.9'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    volumes:
      - .:/app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - indices.analysis.hunspell.dictionary.ignore_case=true
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  importer:
    image: node:18
    container_name: data_importer
    depends_on:
      - elasticsearch
    volumes:
      - ./court_decisions.json:/data/court_decisions.json
      - ./court_decisions_mapping.json:/data/court_decisions_mapping.json
      - ./hunspell:/usr/share/elasticsearch/config/hunspell
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: >
      /bin/sh -c "apt-get update && apt-get install -y wget gnupg && \
      apt-get install -y npm && \
      npm install -g elasticdump && \
      sleep 10 && \
      elasticdump --input=/data/court_decisions.json --output=http://elasticsearch:9200/court_decisions --type=data && \
      elasticdump --input=/data/court_decisions_mapping.json --output=http://elasticsearch:9200/court_decisions --type=mapping"
    restart: "no"


volumes:
  esdata:
