version: '3.9'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    volumes:
      - ./app:/app
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - indices.analysis.hunspell.dictionary.ignore_case=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./hunspell:/usr/share/elasticsearch/config/hunspell
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped

  indexer:
    build: .
    container_name: indexer
    depends_on:
      fastapi:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    command: >
      sh -c "pip install -r /indexing/requirements.txt &&
             python /indexing/main.py"
    volumes:
      - ./indexing:/indexing
      - ./indexing/data:/data
    working_dir: /
    restart: "no"

volumes:
  esdata:
